export enum ServerError {
  EMAIL_ALREADY_ATTRIBUTED,
  HANDLE_RESERVED,
  HANDLE_TAKEN,
  USER_DNE,
  INVALID_TOKEN,
  THEATRE_SLUG_NOT_UNIQUE,
  THEATRE_DNE,
  THREAD_DNE,
  EXPECTED_VALIDATED_DATA,
  INSUFFICIENT_PERMISSIONS,
  BAD_REQUEST,
}
